/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.hcmus.student.sv19127505.SlangDictionary;

import java.awt.CardLayout;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Dictionary dict;
    DictionaryHistory history;
    CardLayout cardLayout;

    private void updateSearchTable(String[][] a) {
        searchTable.setModel(new AbstractTableModel() {
            final String[] columns = {"Name", "Definition"};

            @Override
            public int getRowCount() {
                return a.length;
            }

            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public Object getValueAt(int row, int col) {
                return a[row][col];
            }

            @Override
            public String getColumnName(int index) {
                return columns[index];
            }
        }
        );
    }

    private void updateHistoryTable(String[][] a) {
        historyTable.setModel(new AbstractTableModel() {
            final String[] columns = {"Name", "Definition", "Time"};

            @Override
            public int getRowCount() {
                return a.length;
            }

            @Override
            public int getColumnCount() {
                return 3;
            }

            @Override
            public Object getValueAt(int row, int col) {
                return a[row][col];
            }

            @Override
            public String getColumnName(int index) {
                return columns[index];
            }
        }
        );
    }

    public Main() {
        dict = new Dictionary();
        history = new DictionaryHistory();

        String status = dict.load("data/dict.ser");
        if (!"".equals(status)) {
            System.out.println(status);
            System.out.println("Generating new dictionary... It is recommended to not change the data folder in order to have a faster accessibility next time you run the app.");
            System.out.println(dict.reset("slang.txt").toUpperCase());
        }

        status = history.load("data/history.ser");
        if (!"".equals(status)) {
            System.out.println(status);
            System.out.println("Generating new history... It is recommended to not change the data folder in order to have a faster accessibility next time you run the app.");
        }

        initComponents();

        cardLayout = (CardLayout) (Cards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyWindow = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_Search = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Quiz = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Cards = new javax.swing.JPanel();
        SearchCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filterWord = new javax.swing.JTextField();
        filterDefinition = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        Search_search = new javax.swing.JButton();
        Search_viewHistory = new javax.swing.JButton();
        QuizCard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        EditCard = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        filterWord1 = new javax.swing.JTextField();
        filterDefinition1 = new javax.swing.JTextField();
        Search_search1 = new javax.swing.JButton();
        Search_search2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Search_search3 = new javax.swing.JButton();
        Search_search4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Search_search5 = new javax.swing.JButton();
        Search_search6 = new javax.swing.JButton();

        historyWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        historyWindow.setMinimumSize(new java.awt.Dimension(509, 404));
        historyWindow.setResizable(false);
        historyWindow.setSize(new java.awt.Dimension(509, 404));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(499, 397));
        jPanel2.setMinimumSize(new java.awt.Dimension(499, 397));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(499, 397));

        jLabel12.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel12.setText("History");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(441, 257));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(441, 257));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(441, 257));

        updateHistoryTable(history.to2DArray());
        historyTable.setAutoCreateRowSorter(true);
        historyTable.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        historyTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(historyTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout historyWindowLayout = new javax.swing.GroupLayout(historyWindow.getContentPane());
        historyWindow.getContentPane().setLayout(historyWindowLayout);
        historyWindowLayout.setHorizontalGroup(
            historyWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        historyWindowLayout.setVerticalGroup(
            historyWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Slang Dictionary");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(921, 622));
        setPreferredSize(new java.awt.Dimension(956, 670));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(956, 647));

        btn_Search.setBackground(new java.awt.Color(131, 224, 255));
        btn_Search.setPreferredSize(new java.awt.Dimension(149, 53));
        btn_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SearchMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        jLabel4.setPreferredSize(new java.awt.Dimension(71, 28));

        javax.swing.GroupLayout btn_SearchLayout = new javax.swing.GroupLayout(btn_Search);
        btn_Search.setLayout(btn_SearchLayout);
        btn_SearchLayout.setHorizontalGroup(
            btn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_SearchLayout.setVerticalGroup(
            btn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_SearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_Quiz.setBackground(new java.awt.Color(51, 204, 255));
        btn_Quiz.setPreferredSize(new java.awt.Dimension(149, 53));
        btn_Quiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_QuizMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/puzzle.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quiz");
        jLabel10.setPreferredSize(new java.awt.Dimension(71, 28));

        javax.swing.GroupLayout btn_QuizLayout = new javax.swing.GroupLayout(btn_Quiz);
        btn_Quiz.setLayout(btn_QuizLayout);
        btn_QuizLayout.setHorizontalGroup(
            btn_QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_QuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_QuizLayout.setVerticalGroup(
            btn_QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_QuizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_Edit.setBackground(new java.awt.Color(0, 204, 255));
        btn_Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Edit.setPreferredSize(new java.awt.Dimension(149, 53));
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_EditMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edit");
        jLabel8.setPreferredSize(new java.awt.Dimension(71, 28));

        javax.swing.GroupLayout btn_EditLayout = new javax.swing.GroupLayout(btn_Edit);
        btn_Edit.setLayout(btn_EditLayout);
        btn_EditLayout.setHorizontalGroup(
            btn_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_EditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_EditLayout.setVerticalGroup(
            btn_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_EditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setName(""); // NOI18N
        label1.setText("HCMUS - 19127505");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setName(""); // NOI18N
        label2.setText("Building Java Application");

        jLabel15.setFont(new java.awt.Font("Lato", 1, 35)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("dictionary");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("SLANG");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("1.0");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_Quiz, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel16)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(80, 80, 80)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Quiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel16)
                    .addContainerGap(566, Short.MAX_VALUE)))
        );

        Cards.setBackground(new java.awt.Color(255, 255, 255));
        Cards.setLayout(new java.awt.CardLayout());

        SearchCard.setBackground(new java.awt.Color(255, 255, 255));
        SearchCard.setPreferredSize(new java.awt.Dimension(800, 617));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel1.setText("Search");

        jLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel3.setText("Word Filter:");

        jLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel5.setText("Definition Filter:");

        filterWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterWordActionPerformed(evt);
            }
        });

        filterDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDefinitionActionPerformed(evt);
            }
        });

        updateSearchTable(dict.to2DArray());
        searchTable.setAutoCreateRowSorter(true);
        searchTable.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        searchTable.setToolTipText("");
        searchTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(searchTable);

        Search_search.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search.setText("Search");
        Search_search.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_searchActionPerformed(evt);
            }
        });

        Search_viewHistory.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_viewHistory.setText("View History");
        Search_viewHistory.setToolTipText("");
        Search_viewHistory.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_viewHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchCardLayout = new javax.swing.GroupLayout(SearchCard);
        SearchCard.setLayout(SearchCardLayout);
        SearchCardLayout.setHorizontalGroup(
            SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchCardLayout.createSequentialGroup()
                        .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SearchCardLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(filterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SearchCardLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(filterDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Search_search, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search_viewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        SearchCardLayout.setVerticalGroup(
            SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchCardLayout.createSequentialGroup()
                        .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(filterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(filterDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Search_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_viewHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        Cards.add(SearchCard, "SearchCard");

        QuizCard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel6.setText("Quiz");

        javax.swing.GroupLayout QuizCardLayout = new javax.swing.GroupLayout(QuizCard);
        QuizCard.setLayout(QuizCardLayout);
        QuizCardLayout.setHorizontalGroup(
            QuizCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        QuizCardLayout.setVerticalGroup(
            QuizCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(547, Short.MAX_VALUE))
        );

        Cards.add(QuizCard, "QuizCard");

        EditCard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel11.setText("Edit");

        updateSearchTable(dict.to2DArray());
        searchTable1.setAutoCreateRowSorter(true);
        searchTable1.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        searchTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        searchTable1.setToolTipText("");
        searchTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(searchTable1);

        jLabel13.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel13.setText("Word Filter:");

        jLabel14.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel14.setText("Definition Filter:");

        filterWord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterWord1ActionPerformed(evt);
            }
        });

        filterDefinition1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDefinition1ActionPerformed(evt);
            }
        });

        Search_search1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search1.setText("Search");
        Search_search1.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_search1ActionPerformed(evt);
            }
        });

        Search_search2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search2.setText("Add");
        Search_search2.setToolTipText("");
        Search_search2.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_search2ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        Search_search3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search3.setText("Edit");
        Search_search3.setToolTipText("");
        Search_search3.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_search3ActionPerformed(evt);
            }
        });

        Search_search4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search4.setText("Remove");
        Search_search4.setToolTipText("");
        Search_search4.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_search4ActionPerformed(evt);
            }
        });

        Search_search5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Search_search5.setForeground(new java.awt.Color(255, 0, 0));
        Search_search5.setText("Reset");
        Search_search5.setToolTipText("");
        Search_search5.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_search5ActionPerformed(evt);
            }
        });

        Search_search6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search6.setText("Save");
        Search_search6.setToolTipText("");
        Search_search6.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_search6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditCardLayout = new javax.swing.GroupLayout(EditCard);
        EditCard.setLayout(EditCardLayout);
        EditCardLayout.setHorizontalGroup(
            EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditCardLayout.createSequentialGroup()
                        .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EditCardLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(5, 5, 5)
                                .addComponent(filterWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditCardLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(filterDefinition1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Search_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Search_search2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(Search_search3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(Search_search4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(Search_search5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(Search_search6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditCardLayout.setVerticalGroup(
            EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditCardLayout.createSequentialGroup()
                        .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(filterWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(filterDefinition1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Search_search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditCardLayout.createSequentialGroup()
                        .addComponent(Search_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search_search3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_search4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search_search6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_search5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        Cards.add(EditCard, "EditCard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterWordActionPerformed
    }//GEN-LAST:event_filterWordActionPerformed

    private void filterDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDefinitionActionPerformed
    }//GEN-LAST:event_filterDefinitionActionPerformed

    private void Search_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_searchActionPerformed

        String w = filterWord.getText();
        String d = filterDefinition.getText();
        history.add(w, d);
        HashSet<String> result = new HashSet<>();

        if (!w.isBlank()) {
            for (String word : dict.words.keySet())
                if (word.contains(w))
                    result.add(word);

            if (!d.isBlank())
                result.retainAll(dict.getWords(d));
        } else {

            if (!d.isBlank())
                result.addAll(dict.getWords(d));
            else {
                updateSearchTable(dict.to2DArray());
                return;
            }
        }

        int size = 0;
        if (!result.isEmpty())
            for (String word : result)
                size += dict.getDefinitions(word).size();

        String[][] resultTable = new String[size][2];
        int i = 0;
        for (String word : result)
            for (String definition : dict.getDefinitions(word)) {
                resultTable[i][0] = word;
                resultTable[i++][1] = definition;
            }

        updateSearchTable(resultTable);
    }//GEN-LAST:event_Search_searchActionPerformed

    private void Search_viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_viewHistoryActionPerformed
        // TODO add your handling code here:
        updateHistoryTable(history.to2DArray());
        historyWindow.setVisible(true);
    }//GEN-LAST:event_Search_viewHistoryActionPerformed

    private void setActive(JPanel panel) {
        panel.setBackground(new Color(131, 224, 255));
    }

    private void setInactive(JPanel panel) {
        panel.setBackground(new Color(51, 204, 255));
    }

    private void btn_SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMousePressed
        cardLayout.show(Cards, "SearchCard");
        updateSearchTable(dict.to2DArray());
        setActive(btn_Search);
        setInactive(btn_Quiz);
        setInactive(btn_Edit);
    }//GEN-LAST:event_btn_SearchMousePressed

    private void btn_QuizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuizMousePressed
        cardLayout.show(Cards, "QuizCard");
        setInactive(btn_Search);
        setActive(btn_Quiz);
        setInactive(btn_Edit);

    }//GEN-LAST:event_btn_QuizMousePressed

    private void btn_EditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMousePressed
        cardLayout.show(Cards, "EditCard");
        setInactive(btn_Search);
        setInactive(btn_Quiz);
        setActive(btn_Edit);

    }//GEN-LAST:event_btn_EditMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (dict.isSaved == false) {
            String[] options = new String[]{"Close Anyways", "Cancel", "Save"};
            int confirm = JOptionPane.showOptionDialog(
                    null,
                    "Save changes to the Dictionary before closing?",
                    "Slang Dictionary",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[0]
            );
            switch (confirm) {
                case 0 ->
                    System.exit(0);
                case 1 -> {
                    return;
                }
                case 2 ->
                    System.out.println(dict.save("data/dict.ser"));
            }
        }
        history.save("data/history.ser");
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void Search_search5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_search5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_search5ActionPerformed

    private void Search_search4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_search4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_search4ActionPerformed

    private void Search_search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_search3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_search3ActionPerformed

    private void Search_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_search2ActionPerformed

    private void Search_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_search1ActionPerformed

    private void filterDefinition1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDefinition1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterDefinition1ActionPerformed

    private void filterWord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterWord1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterWord1ActionPerformed

    private void Search_search6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_search6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_search6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JPanel EditCard;
    private javax.swing.JPanel QuizCard;
    private javax.swing.JPanel SearchCard;
    private javax.swing.JButton Search_search;
    private javax.swing.JButton Search_search1;
    private javax.swing.JButton Search_search2;
    private javax.swing.JButton Search_search3;
    private javax.swing.JButton Search_search4;
    private javax.swing.JButton Search_search5;
    private javax.swing.JButton Search_search6;
    private javax.swing.JButton Search_viewHistory;
    private javax.swing.JPanel btn_Edit;
    private javax.swing.JPanel btn_Quiz;
    private javax.swing.JPanel btn_Search;
    private javax.swing.JTextField filterDefinition;
    private javax.swing.JTextField filterDefinition1;
    private javax.swing.JTextField filterWord;
    private javax.swing.JTextField filterWord1;
    private javax.swing.JTable historyTable;
    private javax.swing.JFrame historyWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTable searchTable;
    private javax.swing.JTable searchTable1;
    // End of variables declaration//GEN-END:variables
}
