/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.hcmus.student.sv19127505.SlangDictionary;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.event.*;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Dictionary dict;
    DictionaryHistory history;
    CardLayout cardLayout;

    final String[] searchColumns = {"Word", "Definition"};
    final String[] historyColumns = {"Word", "Definition", "Time"};

    private void updateTable(JTable table, String[][] tableContent, String[] columns) {
        table.setModel(new AbstractTableModel() {

            @Override
            public int getRowCount() {
                return tableContent.length;
            }

            @Override
            public int getColumnCount() {
                return columns.length;
            }

            @Override
            public Object getValueAt(int row, int col) {
                return tableContent[row][col];
            }

            @Override
            public String getColumnName(int index) {
                return columns[index];
            }
        }
        );

        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(0).setMinWidth(100);
        table.getColumnModel().getColumn(0).setMaxWidth(100);
    }

    public Main() {
        dict = new Dictionary();
        history = new DictionaryHistory();

        String status = dict.load("data/dict.ser");
        if (!"".equals(status)) {
            System.out.println(status);
            System.out.println("Generating new dictionary... It is recommended to not change the data folder in order to have a faster accessibility next time you run the app.");
            System.out.println(dict.reset("slang.txt").toUpperCase());
        }

        status = history.load("data/history.ser");
        if (!"".equals(status)) {
            System.out.println(status);
            System.out.println("Generating new history... It is recommended to not change the data folder in order to have a faster accessibility next time you run the app.");
        }

        initComponents();

        updateTable(searchTable, dict.to2DArray(), searchColumns);
        cardLayout = (CardLayout) (Cards.getLayout());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyWindow = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        addWindow = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Add_word = new javax.swing.JTextField();
        Add_definition = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Add_confirm = new javax.swing.JButton();
        Add_cancel = new javax.swing.JButton();
        editWindow = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Edit_word = new javax.swing.JTextField();
        Edit_definition = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Edit_confirm = new javax.swing.JButton();
        Edit_cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_Search = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Quiz = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Cards = new javax.swing.JPanel();
        SearchCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Search_filterWord = new javax.swing.JTextField();
        Search_filterDefinition = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        Search_search = new javax.swing.JButton();
        Search_viewHistory = new javax.swing.JButton();
        QuizCard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        EditCard = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Edit_filterWord = new javax.swing.JTextField();
        Edit_filterDefinition = new javax.swing.JTextField();
        Edit_search = new javax.swing.JButton();
        Edit_add = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Edit_edit = new javax.swing.JButton();
        Edit_remove = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Edit_reset = new javax.swing.JButton();
        Edit_save = new javax.swing.JButton();

        historyWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        historyWindow.setMinimumSize(new java.awt.Dimension(509, 404));
        historyWindow.setResizable(false);
        historyWindow.setSize(new java.awt.Dimension(509, 404));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(499, 397));
        jPanel2.setMinimumSize(new java.awt.Dimension(499, 397));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(499, 397));

        jLabel12.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel12.setText("History");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(441, 257));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(441, 257));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(441, 257));

        updateTable(historyTable, history.to2DArray(), historyColumns);
        historyTable.setAutoCreateRowSorter(true);
        historyTable.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        historyTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(historyTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout historyWindowLayout = new javax.swing.GroupLayout(historyWindow.getContentPane());
        historyWindow.getContentPane().setLayout(historyWindowLayout);
        historyWindowLayout.setHorizontalGroup(
            historyWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        historyWindowLayout.setVerticalGroup(
            historyWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addWindow.setMaximumSize(new java.awt.Dimension(397, 266));
        addWindow.setMinimumSize(new java.awt.Dimension(397, 266));
        addWindow.setPreferredSize(new java.awt.Dimension(397, 266));
        addWindow.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(397, 266));
        jPanel4.setMinimumSize(new java.awt.Dimension(397, 266));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(397, 266));

        jLabel18.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel18.setText("Add");

        Add_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_wordActionPerformed(evt);
            }
        });

        Add_definition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_definitionActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel19.setText("New Word:");

        jLabel20.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel20.setText("New Definition:");

        Add_confirm.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Add_confirm.setText("Confirm");
        Add_confirm.setToolTipText("");
        Add_confirm.setPreferredSize(new java.awt.Dimension(77, 27));
        Add_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_confirmActionPerformed(evt);
            }
        });

        Add_cancel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Add_cancel.setText("Cancel");
        Add_cancel.setToolTipText("");
        Add_cancel.setPreferredSize(new java.awt.Dimension(77, 27));
        Add_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Add_word, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(Add_definition)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Add_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Add_word, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Add_definition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addWindowLayout = new javax.swing.GroupLayout(addWindow.getContentPane());
        addWindow.getContentPane().setLayout(addWindowLayout);
        addWindowLayout.setHorizontalGroup(
            addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addWindowLayout.setVerticalGroup(
            addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editWindow.setMaximumSize(new java.awt.Dimension(397, 266));
        editWindow.setMinimumSize(new java.awt.Dimension(397, 266));
        editWindow.setPreferredSize(new java.awt.Dimension(397, 266));
        editWindow.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(397, 266));
        jPanel5.setMinimumSize(new java.awt.Dimension(397, 266));
        jPanel5.setName(""); // NOI18N

        jLabel21.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel21.setText("Edit");

        Edit_word.setEnabled(false);
        Edit_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_wordActionPerformed(evt);
            }
        });

        Edit_definition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_definitionActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel22.setText("Word:");

        jLabel23.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel23.setText("Definition:");

        Edit_confirm.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_confirm.setText("Confirm");
        Edit_confirm.setToolTipText("");
        Edit_confirm.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_confirmActionPerformed(evt);
            }
        });

        Edit_cancel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_cancel.setText("Cancel");
        Edit_cancel.setToolTipText("");
        Edit_cancel.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Edit_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Edit_word, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(Edit_definition)
                            .addComponent(Edit_confirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Edit_word, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Edit_definition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Edit_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editWindowLayout = new javax.swing.GroupLayout(editWindow.getContentPane());
        editWindow.getContentPane().setLayout(editWindowLayout);
        editWindowLayout.setHorizontalGroup(
            editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editWindowLayout.setVerticalGroup(
            editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Slang Dictionary");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(921, 622));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(956, 647));

        btn_Search.setBackground(new java.awt.Color(131, 224, 255));
        btn_Search.setPreferredSize(new java.awt.Dimension(149, 53));
        btn_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SearchMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        jLabel4.setPreferredSize(new java.awt.Dimension(71, 28));

        javax.swing.GroupLayout btn_SearchLayout = new javax.swing.GroupLayout(btn_Search);
        btn_Search.setLayout(btn_SearchLayout);
        btn_SearchLayout.setHorizontalGroup(
            btn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_SearchLayout.setVerticalGroup(
            btn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_SearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_Quiz.setBackground(new java.awt.Color(51, 204, 255));
        btn_Quiz.setPreferredSize(new java.awt.Dimension(149, 53));
        btn_Quiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_QuizMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/puzzle.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quiz");
        jLabel10.setPreferredSize(new java.awt.Dimension(71, 28));

        javax.swing.GroupLayout btn_QuizLayout = new javax.swing.GroupLayout(btn_Quiz);
        btn_Quiz.setLayout(btn_QuizLayout);
        btn_QuizLayout.setHorizontalGroup(
            btn_QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_QuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_QuizLayout.setVerticalGroup(
            btn_QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_QuizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_Edit.setBackground(new java.awt.Color(0, 204, 255));
        btn_Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Edit.setPreferredSize(new java.awt.Dimension(149, 53));
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_EditMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edit");
        jLabel8.setPreferredSize(new java.awt.Dimension(71, 28));

        javax.swing.GroupLayout btn_EditLayout = new javax.swing.GroupLayout(btn_Edit);
        btn_Edit.setLayout(btn_EditLayout);
        btn_EditLayout.setHorizontalGroup(
            btn_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_EditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_EditLayout.setVerticalGroup(
            btn_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_EditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setName(""); // NOI18N
        label1.setText("HCMUS - 19127505");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setName(""); // NOI18N
        label2.setText("Building Java Application");

        jLabel15.setFont(new java.awt.Font("Lato", 1, 35)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("dictionary");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("SLANG");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("1.0");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_Quiz, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel16)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(80, 80, 80)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Quiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel16)
                    .addContainerGap(566, Short.MAX_VALUE)))
        );

        Cards.setBackground(new java.awt.Color(255, 255, 255));
        Cards.setLayout(new java.awt.CardLayout());

        SearchCard.setBackground(new java.awt.Color(255, 255, 255));
        SearchCard.setPreferredSize(new java.awt.Dimension(800, 617));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel1.setText("Search");

        jLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel3.setText("Word Filter:");

        jLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel5.setText("Definition Filter:");

        Search_filterWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_filterWordActionPerformed(evt);
            }
        });

        Search_filterDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_filterDefinitionActionPerformed(evt);
            }
        });

        jScrollPane2.setToolTipText("");

        updateTable(searchTable, dict.to2DArray(), searchColumns);
        searchTable.setAutoCreateRowSorter(true);
        searchTable.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        searchTable.setToolTipText("");
        searchTable.setRowHeight(20);
        searchTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(searchTable);

        Search_search.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_search.setText("Search");
        Search_search.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_searchActionPerformed(evt);
            }
        });

        Search_viewHistory.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Search_viewHistory.setText("View History");
        Search_viewHistory.setToolTipText("");
        Search_viewHistory.setPreferredSize(new java.awt.Dimension(77, 27));
        Search_viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_viewHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchCardLayout = new javax.swing.GroupLayout(SearchCard);
        SearchCard.setLayout(SearchCardLayout);
        SearchCardLayout.setHorizontalGroup(
            SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchCardLayout.createSequentialGroup()
                        .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SearchCardLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(Search_filterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SearchCardLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Search_filterDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Search_search, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search_viewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        SearchCardLayout.setVerticalGroup(
            SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchCardLayout.createSequentialGroup()
                        .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Search_filterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Search_filterDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Search_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_viewHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        Cards.add(SearchCard, "SearchCard");

        QuizCard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel6.setText("Quiz");

        javax.swing.GroupLayout QuizCardLayout = new javax.swing.GroupLayout(QuizCard);
        QuizCard.setLayout(QuizCardLayout);
        QuizCardLayout.setHorizontalGroup(
            QuizCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        QuizCardLayout.setVerticalGroup(
            QuizCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(547, Short.MAX_VALUE))
        );

        Cards.add(QuizCard, "QuizCard");

        EditCard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel11.setText("Edit");

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        updateTable(editTable, dict.to2DArray(), searchColumns);
        editTable.setAutoCreateRowSorter(true);
        editTable.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        editTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        editTable.setToolTipText("");
        editTable.setRowHeight(20);
        editTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(editTable);
        editTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){

            public void valueChanged(ListSelectionEvent event){
                if (!event.getValueIsAdjusting() && editTable.getSelectedRow() != -1
                    && editTable.getSelectedRowCount() == 1)
                {
                    Edit_edit.setEnabled(true);
                    Edit_remove.setEnabled(true);
                }
                else{
                    Edit_edit.setEnabled(false);
                    Edit_remove.setEnabled(false);
                }
            }

        });

        jLabel13.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel13.setText("Word Filter:");

        jLabel14.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel14.setText("Definition Filter:");

        Edit_filterWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_filterWordActionPerformed(evt);
            }
        });

        Edit_filterDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_filterDefinitionActionPerformed(evt);
            }
        });

        Edit_search.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_search.setText("Search");
        Edit_search.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_searchActionPerformed(evt);
            }
        });

        Edit_add.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_add.setText("Add");
        Edit_add.setToolTipText("");
        Edit_add.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_addActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        Edit_edit.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_edit.setText("Edit");
        Edit_edit.setToolTipText("");
        Edit_edit.setEnabled(false);
        Edit_edit.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_editActionPerformed(evt);
            }
        });

        Edit_remove.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_remove.setText("Remove");
        Edit_remove.setToolTipText("");
        Edit_remove.setEnabled(false);
        Edit_remove.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_removeActionPerformed(evt);
            }
        });

        Edit_reset.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Edit_reset.setForeground(new java.awt.Color(255, 0, 0));
        Edit_reset.setText("Reset");
        Edit_reset.setToolTipText("");
        Edit_reset.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_resetActionPerformed(evt);
            }
        });

        Edit_save.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Edit_save.setText("Save");
        Edit_save.setToolTipText("");
        Edit_save.setPreferredSize(new java.awt.Dimension(77, 27));
        Edit_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditCardLayout = new javax.swing.GroupLayout(EditCard);
        EditCard.setLayout(EditCardLayout);
        EditCardLayout.setHorizontalGroup(
            EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditCardLayout.createSequentialGroup()
                        .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EditCardLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(5, 5, 5)
                                .addComponent(Edit_filterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditCardLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Edit_filterDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Edit_search, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Edit_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(Edit_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(Edit_remove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(Edit_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(Edit_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditCardLayout.setVerticalGroup(
            EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditCardLayout.createSequentialGroup()
                        .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Edit_filterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Edit_filterDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Edit_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(EditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditCardLayout.createSequentialGroup()
                        .addComponent(Edit_add, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Edit_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Edit_save, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        Cards.add(EditCard, "EditCard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_filterWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_filterWordActionPerformed
    }//GEN-LAST:event_Search_filterWordActionPerformed

    private void Search_filterDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_filterDefinitionActionPerformed
    }//GEN-LAST:event_Search_filterDefinitionActionPerformed

    private void Search_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_searchActionPerformed
        String w = Search_filterWord.getText();
        String d = Search_filterDefinition.getText();
        history.add(w, d);
        HashSet<String> result = new HashSet<>();

        if (!w.isBlank()) {
            for (String word : dict.words.keySet())
                if (word.contains(w))
                    result.add(word);

            if (!d.isBlank())
                result.retainAll(dict.getWords(d));
        } else if (!d.isBlank())
            result.addAll(dict.getWords(d));
        else {
            updateTable(searchTable, dict.to2DArray(), searchColumns);
            return;
        }

        int size = 0;
        if (!result.isEmpty())
            for (String word : result)
                size += dict.getDefinitions(word).size();

        String[][] resultTable = new String[size][2];
        int i = 0;
        for (String word : result)
            for (String definition : dict.getDefinitions(word)) {
                resultTable[i][0] = word;
                resultTable[i++][1] = definition;
            }

        updateTable(searchTable, resultTable, searchColumns);
    }//GEN-LAST:event_Search_searchActionPerformed

    private void Search_viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_viewHistoryActionPerformed
        updateTable(historyTable, history.to2DArray(), historyColumns);
        historyWindow.setVisible(true);
    }//GEN-LAST:event_Search_viewHistoryActionPerformed

    private void setActive(JPanel panel) {
        panel.setBackground(new Color(131, 224, 255));
    }

    private void setInactive(JPanel panel) {
        panel.setBackground(new Color(51, 204, 255));
    }

    private void btn_SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMousePressed
        cardLayout.show(Cards, "SearchCard");

        Search_filterWord.setText("");
        Search_filterDefinition.setText("");
        updateTable(searchTable, dict.to2DArray(), searchColumns);

        setActive(btn_Search);
        setInactive(btn_Quiz);
        setInactive(btn_Edit);
    }//GEN-LAST:event_btn_SearchMousePressed

    private void btn_QuizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuizMousePressed
        cardLayout.show(Cards, "QuizCard");
        setInactive(btn_Search);
        setActive(btn_Quiz);
        setInactive(btn_Edit);

    }//GEN-LAST:event_btn_QuizMousePressed

    private void btn_EditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMousePressed
        cardLayout.show(Cards, "EditCard");

        Edit_filterWord.setText("");
        Edit_filterDefinition.setText("");
        updateTable(editTable, dict.to2DArray(), searchColumns);

        setInactive(btn_Search);
        setInactive(btn_Quiz);
        setActive(btn_Edit);
    }//GEN-LAST:event_btn_EditMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (dict.isSaved == false) {
            String[] options = new String[]{"Close Anyways", "Cancel", "Save"};
            int confirm = JOptionPane.showOptionDialog(
                    null,
                    "Save changes to the Dictionary before closing?",
                    "Slang Dictionary",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[2]
            );
            switch (confirm) {
                case 0 ->
                    System.exit(0);
                case 1 -> {
                    return;
                }
                case 2 ->
                    System.out.println(dict.save("data/dict.ser"));
            }
        }
        history.save("data/history.ser");
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void Edit_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_resetActionPerformed

    private void Edit_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_removeActionPerformed

    String currentSelectedDefinition;

    private void Edit_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_editActionPerformed
        // TODO add your handling code here:
        currentSelectedDefinition = (String) editTable.getValueAt(editTable.getSelectedRow(), 1);

        Edit_word.setText((String) editTable.getValueAt(editTable.getSelectedRow(), 0));
        Edit_definition.setText(currentSelectedDefinition);
        editWindow.setVisible(true);
    }//GEN-LAST:event_Edit_editActionPerformed

    private void Edit_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_addActionPerformed
        Add_definition.setText("");
        addWindow.setVisible(true);
    }//GEN-LAST:event_Edit_addActionPerformed

    private void Edit_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_searchActionPerformed
        String w = Edit_filterWord.getText();
        String d = Edit_filterDefinition.getText();

        HashSet<String> result = new HashSet<>();

        if (!w.isBlank()) {
            for (String word : dict.words.keySet())
                if (word.contains(w))
                    result.add(word);

            if (!d.isBlank())
                result.retainAll(dict.getWords(d));
        } else if (!d.isBlank())
            result.addAll(dict.getWords(d));
        else {
            updateTable(editTable, dict.to2DArray(), searchColumns);
            return;
        }

        int size = 0;
        if (!result.isEmpty())
            for (String word : result)
                size += dict.getDefinitions(word).size();

        String[][] resultTable = new String[size][2];
        int i = 0;
        for (String word : result)
            for (String definition : dict.getDefinitions(word)) {
                resultTable[i][0] = word;
                resultTable[i++][1] = definition;
            }

        updateTable(editTable, resultTable, searchColumns);
    }//GEN-LAST:event_Edit_searchActionPerformed

    private void Edit_filterDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_filterDefinitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_filterDefinitionActionPerformed

    private void Edit_filterWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_filterWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_filterWordActionPerformed

    private void Edit_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_saveActionPerformed

    private void Add_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_wordActionPerformed

    private void Add_definitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_definitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_definitionActionPerformed

    private void Add_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_confirmActionPerformed
        String w = Add_word.getText();
        String d = Add_definition.getText();

        if ("".equals(w))
            JOptionPane.showMessageDialog(null, "Word must not be null.");
        else if ("".equals(d))
            JOptionPane.showMessageDialog(null, "Definition must not be null.");
        else if (dict.words.containsKey(w)) {
            String[] options = new String[]{"Overwrite", "Cancel", "Duplicate"};
            int confirm = JOptionPane.showOptionDialog(
                    null,
                    "Key existed in dictionary, duplicate?",
                    "Slang Dictionary",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[2]
            );
            switch (confirm) {
                case 0 ->
                    dict.overwrite(w, d);
                case 1 -> {
                    return;
                }
                case 2 ->
                    dict.put(w, d);
            }

            Edit_search.getActionListeners()[0].actionPerformed(null);
            addWindow.dispose();

        } else {

            dict.put(w, d);
            Edit_search.getActionListeners()[0].actionPerformed(null);
            addWindow.dispose();
        }
    }//GEN-LAST:event_Add_confirmActionPerformed

    private void Add_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_cancelActionPerformed
        addWindow.dispose();
    }//GEN-LAST:event_Add_cancelActionPerformed

    private void Edit_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_wordActionPerformed

    private void Edit_definitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_definitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_definitionActionPerformed

    private void Edit_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_confirmActionPerformed
        String w = Edit_word.getText();
        String d = Edit_definition.getText();

        HashSet<String> ws = dict.getDefinitions(w);
        if (d.equals(currentSelectedDefinition))
            editWindow.dispose();
        else if (ws.contains(d))
            JOptionPane.showMessageDialog(null, "This definition already existed.");
        else {
            dict.replace(w, currentSelectedDefinition, d);
            Edit_search.getActionListeners()[0].actionPerformed(null);
            editWindow.dispose();
        }
    }//GEN-LAST:event_Edit_confirmActionPerformed

    private void Edit_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_cancel;
    private javax.swing.JButton Add_confirm;
    private javax.swing.JTextField Add_definition;
    private javax.swing.JTextField Add_word;
    private javax.swing.JPanel Cards;
    private javax.swing.JPanel EditCard;
    private javax.swing.JButton Edit_add;
    private javax.swing.JButton Edit_cancel;
    private javax.swing.JButton Edit_confirm;
    private javax.swing.JTextField Edit_definition;
    private javax.swing.JButton Edit_edit;
    private javax.swing.JTextField Edit_filterDefinition;
    private javax.swing.JTextField Edit_filterWord;
    private javax.swing.JButton Edit_remove;
    private javax.swing.JButton Edit_reset;
    private javax.swing.JButton Edit_save;
    private javax.swing.JButton Edit_search;
    private javax.swing.JTextField Edit_word;
    private javax.swing.JPanel QuizCard;
    private javax.swing.JPanel SearchCard;
    private javax.swing.JTextField Search_filterDefinition;
    private javax.swing.JTextField Search_filterWord;
    private javax.swing.JButton Search_search;
    private javax.swing.JButton Search_viewHistory;
    private javax.swing.JFrame addWindow;
    private javax.swing.JPanel btn_Edit;
    private javax.swing.JPanel btn_Quiz;
    private javax.swing.JPanel btn_Search;
    private javax.swing.JTable editTable;
    private javax.swing.JFrame editWindow;
    private javax.swing.JTable historyTable;
    private javax.swing.JFrame historyWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTable searchTable;
    // End of variables declaration//GEN-END:variables
}
